// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	v1 "github.com/hi20160616/fetchnews-api/proto/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FetchZaobaoClient is the client API for FetchZaobao service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FetchZaobaoClient interface {
	ListArticles(ctx context.Context, in *v1.ListArticlesRequest, opts ...grpc.CallOption) (*v1.ListArticlesResponse, error)
	GetArticle(ctx context.Context, in *v1.GetArticleRequest, opts ...grpc.CallOption) (*v1.Article, error)
	SearchArticles(ctx context.Context, in *v1.SearchArticlesRequest, opts ...grpc.CallOption) (*v1.SearchArticlesResponse, error)
}

type fetchZaobaoClient struct {
	cc grpc.ClientConnInterface
}

func NewFetchZaobaoClient(cc grpc.ClientConnInterface) FetchZaobaoClient {
	return &fetchZaobaoClient{cc}
}

func (c *fetchZaobaoClient) ListArticles(ctx context.Context, in *v1.ListArticlesRequest, opts ...grpc.CallOption) (*v1.ListArticlesResponse, error) {
	out := new(v1.ListArticlesResponse)
	err := c.cc.Invoke(ctx, "/fetchnews.zaobao.v1.FetchZaobao/ListArticles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fetchZaobaoClient) GetArticle(ctx context.Context, in *v1.GetArticleRequest, opts ...grpc.CallOption) (*v1.Article, error) {
	out := new(v1.Article)
	err := c.cc.Invoke(ctx, "/fetchnews.zaobao.v1.FetchZaobao/GetArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fetchZaobaoClient) SearchArticles(ctx context.Context, in *v1.SearchArticlesRequest, opts ...grpc.CallOption) (*v1.SearchArticlesResponse, error) {
	out := new(v1.SearchArticlesResponse)
	err := c.cc.Invoke(ctx, "/fetchnews.zaobao.v1.FetchZaobao/SearchArticles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FetchZaobaoServer is the server API for FetchZaobao service.
// All implementations must embed UnimplementedFetchZaobaoServer
// for forward compatibility
type FetchZaobaoServer interface {
	ListArticles(context.Context, *v1.ListArticlesRequest) (*v1.ListArticlesResponse, error)
	GetArticle(context.Context, *v1.GetArticleRequest) (*v1.Article, error)
	SearchArticles(context.Context, *v1.SearchArticlesRequest) (*v1.SearchArticlesResponse, error)
	mustEmbedUnimplementedFetchZaobaoServer()
}

// UnimplementedFetchZaobaoServer must be embedded to have forward compatible implementations.
type UnimplementedFetchZaobaoServer struct {
}

func (UnimplementedFetchZaobaoServer) ListArticles(context.Context, *v1.ListArticlesRequest) (*v1.ListArticlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArticles not implemented")
}
func (UnimplementedFetchZaobaoServer) GetArticle(context.Context, *v1.GetArticleRequest) (*v1.Article, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticle not implemented")
}
func (UnimplementedFetchZaobaoServer) SearchArticles(context.Context, *v1.SearchArticlesRequest) (*v1.SearchArticlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchArticles not implemented")
}
func (UnimplementedFetchZaobaoServer) mustEmbedUnimplementedFetchZaobaoServer() {}

// UnsafeFetchZaobaoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FetchZaobaoServer will
// result in compilation errors.
type UnsafeFetchZaobaoServer interface {
	mustEmbedUnimplementedFetchZaobaoServer()
}

func RegisterFetchZaobaoServer(s grpc.ServiceRegistrar, srv FetchZaobaoServer) {
	s.RegisterService(&FetchZaobao_ServiceDesc, srv)
}

func _FetchZaobao_ListArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FetchZaobaoServer).ListArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fetchnews.zaobao.v1.FetchZaobao/ListArticles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FetchZaobaoServer).ListArticles(ctx, req.(*v1.ListArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FetchZaobao_GetArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FetchZaobaoServer).GetArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fetchnews.zaobao.v1.FetchZaobao/GetArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FetchZaobaoServer).GetArticle(ctx, req.(*v1.GetArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FetchZaobao_SearchArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.SearchArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FetchZaobaoServer).SearchArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fetchnews.zaobao.v1.FetchZaobao/SearchArticles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FetchZaobaoServer).SearchArticles(ctx, req.(*v1.SearchArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FetchZaobao_ServiceDesc is the grpc.ServiceDesc for FetchZaobao service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FetchZaobao_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fetchnews.zaobao.v1.FetchZaobao",
	HandlerType: (*FetchZaobaoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListArticles",
			Handler:    _FetchZaobao_ListArticles_Handler,
		},
		{
			MethodName: "GetArticle",
			Handler:    _FetchZaobao_GetArticle_Handler,
		},
		{
			MethodName: "SearchArticles",
			Handler:    _FetchZaobao_SearchArticles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/fetchnews/zaobao/v1/fetchnews.proto",
}
